name: Test Playwright Tweet Checker

on:
  workflow_dispatch: # Manual trigger dari GitHub UI

jobs:
  tweet-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run script (1x loop only)
        run: |
          python tweet_check.py
